clear;
funName = 'grlvq';
dataSets = {'lorenz'};
dataPath = '/home/jelle/RUG/FTP/implementation/timeseries_tests/data';
resultsPath = '/home/jelle/RUG/FTP/implementation/timeseries_tests/results';
impPath = '/home/jelle/RUG/FTP/implementation/timeseries_tests/';
addpath(genpath(impPath));


preproc = {'naive'};

grlvqParams = fn_exp_paramGenerator(struct(...
        'PrototypesPerClass',1, ...
        'regularization',0, ...
        'nb_epochs', 800, ...
        'Display', 'off', ...
        'optimization','sgd', ...
        'DiffMinChange',0.001, ...
        'initialRelevances', [] ...
    ),...
    struct(...
));


params = {grlvqParams};
runs = 1;

expermiments = fn_exp_generator(funName,dataSets,dataPath,preproc,runs, params);
results = fn_exp_runner(expermiments);
fn_exp_save_results(results, resultsPath);