clear;

dataDir = '/home/jelle/Desktop/gml-new/';

dirFilePath = dir(dataDir);
fileNames = {dirFilePath.name};

resultTable = [];
skip = 0;

for fileIdx = 3 : length(fileNames)
    
    fileStruct = dirFilePath(fileIdx);
    load([dataDir,fileStruct.name]);
    disp([dataDir,fileStruct.name]);
    
    methodNames = strsplit(result.function(8:end),'_');
    lvqMethodName = methodNames{end};
    
    if isa(result.results{1},'MException');continue;end;
    
    [train, test] = getErrorRates(result , lvqMethodName);
    [meanDist1, stdDist1, meanDist2, stdDist2] = getFdistance(result, methodNames);
    [avgCosts,costs] = getCosts(result,lvqMethodName);
    
    resultTable = [resultTable;struct(...
        'dataset', result.dataSetName,...
        'method', result.function(8:end),...
        'pre', result.preprocessing(8:end),...       
        'trainAVG',train(1,1),...
        'trainSTD',train(1,2),...
        'testAVG',test(1,1),...
        'testSTD',test(1,2),...
        'meanDist1',meanDist1,...
        'stdDist1',stdDist1,...
        'meanDist2',meanDist2,...
        'stdDist2',stdDist2,...
        'avgCosts',avgCosts,...
        'costs',costs...
        )];
      
end